# Site settings
title: Vahit Tabak
description: 'LPIC-2, SUSE CLA, VCP-DCV, NCDA, ITIL'
url: 'http://vahittabak.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'vahittabak'

author:
  name: 'Vahit Tabak'
  email: vahit@vahittabak.com
  twitter_username: vahittabak
  facebook_username: vahittabak
  github_username: vahittabak 
  linkedin_username: vahittabak

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
